## Enable Debug mode for logger.
debug: true

http:
  listen_addr: ":9098"

clickhouse:
  host: localhost
  port: 9000
  db: test
  user: clickhouse_me
  password: qwerty
  conn_max_lifetime: 4s
  max_open_conns: 10
  MaxIdleConns: 10

nats:
  client_name: nats_to_ch
  server: nats://localhost:4222
  max_reconnect: -1
  reconnect_wait: 10
  connect_timeout: 10
  user: localuser
  password: localpassword
  max_wait: 10

subjects: [
  {
    ## Name of subject
    name: "test",
    ## Name of queue
    queue: "testQueue",
    ## Name of table for insert
    table_name: "testCash",
    ## Enable Buffer mode, when messages from Nats stacks in buffer.
    use_buffer: false,
  },
  {
    ## Name of subject
    name: "test1",
    ## Name of queue
    queue: "test1Queue",
    ## Name of table for insert
    table_name: "testCash",
    ## Enable Buffer mode, when messages from Nats stacks in buffer.
    use_buffer: true,
    buffer_config: {
      ## Max size of buffer for starting to drain. Must be greater than 0.
      max_size: 10,
      ## Max timeout of buffer for starting to drain. Must be greater than 0.
      max_wait: 60s,
    },
  }
]
