# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: gotest
    runs-on: ubuntu-latest
    services:
      nats:
        image: nats
        ports: ['4222:4222']
        
      clickhouse:
        image: clickhouse/clickhouse-server
        ports: ['9000:9000']
        
    steps:
    - name: Set up Clickhouse
      run: |
        sudo apt-get install -y apt-transport-https ca-certificates dirmngr
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 8919F6BD2B48D754
        echo "deb https://packages.clickhouse.com/deb stable main" | sudo tee \
            /etc/apt/sources.list.d/clickhouse.list
        sudo apt-get update
        sudo apt-get install -y clickhouse-client
        sudo clickhouse-client --query "CREATE DATABASE IF NOT EXISTS test"
        sudo clickhouse-client --query "CREATE TABLE IF NOT EXISTS test.test (Subject String, CreateDateTime DateTime, Content String) ENGINE = Memory"
        sudo clickhouse-client --query "INSERT INTO test.test VALUES ('test', now(), 'test')"
        sudo clickhouse-client --query "SELECT * FROM test.test"

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Set up Nats
      run: |
        go install github.com/nats-io/nats-server/v2@latest

    - name: Check out code
      uses: actions/checkout@v4

    - name: Build
      run: go build -v ./...

    - name: Run Unit tests.
      run: go test -v ./...

    - name: Update coverage report
      uses: ncruces/go-coverage-report@21fa4b59396f242b81896a3cd212a463589b6742
      with:
        report: 'false'
        chart: 'true'
        amend: 'false'
